services:
  - type: web
    name: thanvi-portfolio
    env: static
    branch: main
    repo: https://github.com/thanvi-nagalla/thanvi-portfolio
    buildCommand: npm ci && npm run build
    staticPublishPath: build
